config/routes.rb
RecipeEbook::Application.routes.draw do
  root :to => "recipes#index"
  resources :recipes do
    resources :instructions
  end
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :recipe
  validates :ingredient, :presence => true
  validates :directions, :presence => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  validates :title, :presence => true

  has_many :instructions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_filter :find_recipe
  before_filter :find_instruction, :only => [:show, :edit, :update, :destroy]

  def new
    @instruction = @recipe.instructions.build
  end

  def edit
    @instruction = Instruction.find(params[:id])
  end

  def create
    @instruction = @recipe.instructions.build(instruction_params)
    if @instruction.save
      flash[:notice] = "Instructions have been created."
      redirect_to [@recipe, @instruction]
    else
      flash[:alert] = "Instructions have not been created."
      render :action => "new"
    end
  end

  def show
    @instruction = Instruction.find(params[:id])
  end


  def update
    if @instruction.update_attributes(params[:instruction]) #anytime writing to db need (instruction_params)
      flash[:notice] = "Instructions have been updated."
      redirect_to [@recipe, @instruction]
    else
      flash[:alert] = "Instructions have not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @instruction = Instruction.find(params[:id])
    @instruction.destroy
    flash[:notice] = "Instruction have been deleted."
    redirect_to instruction_path
  end

  private
  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def find_instruction
    @instruction = @recipe.instructions.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The instructions you were looking for could not be found."
    redirect_to recipes_path
  end

  def instruction_params
    params.require(:instruction).permit( :ingredient, :directions)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :find_recipe, :only => [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Recipe has been created."
      redirect_to @recipe
    else
      flash[:alert] = "Recipe has not been created."
      render :action => "new"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params) #anytime writing to db need (recipe_params)
      flash[:notice] = "Recipe has been updated."
      redirect_to @recipe
    else
      flash[:alert] = "Recipe has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Recipe has been deleted."
    redirect_to recipes_path
  end

  private
  def find_recipe
    @recipe = Recipe.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The recipe you were looking for could not be found."
    redirect_to recipes_path
  end

  def recipe_params
    params.require(:recipe).permit( :title, :description, :preptime, :servings)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Recipe").join(" - ")
      end
    end
  end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/instructions/_form.html.erb
<%= form_for [@recipe, @instruction] do |f| %>
  <%= f.error_messages %>
    <p>
      <%= f.label :ingredient, "Ingredients with measurement" %><br>
      <%= f.text_area :ingredient %>
    </p>
    <p>
      <%= f.label :directions, "Directions with procedures" %><br>
      <%= f.text_area :directions %>
    </p>
  <%= f.submit %>
<% end %>

app/views/instructions/edit.html.erb
<h2>Edit instruction</h2>
<%= render "form" %>

app/views/instructions/new.html.erb
<h2>New Instruction </h2>
<h3><%= @recipe.title %></h3>
<%= render "form" %>

app/views/instructions/show.html.erb
<%= link_to "Back to Recipes Page", recipes_path %>
<div id='instructions'>
  <h2><%= title(@recipe.title, "Recipes") %></h2>
  <h2><%= @recipe.title %></h2>

  <p>Ingredient: <%= @instruction.ingredient %></p>
  <p>Directions: <%= @instruction.directions %></p>
  <%= link_to "New Instruction", new_recipe_instruction_path(@recipe) %>
  <%= link_to "Edit Instruction", [:edit, @recipe, @instruction] %>
  <%= link_to "Delete Instruction", [@recipe, @instruction],
     :method => :delete,
     data: { confirm: "Are you sure you want to delete these instructions?" }%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Recipes - Ebook" %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description, "Meal Type" %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :preptime, "Prep Time" %><br />
    <%= f.text_field :preptime %>
  </p>
  <p>
    <%= f.label :servings %><br />
    <%= f.text_field :servings %>
  </p>
  <%= f.submit %>
  <%= f.error_messages %>
<% end %>

app/views/recipes/edit.html.erb
<h2>Edit recipe</h2>
<%= render "form" %>

app/views/recipes/index.html.erb
<%= link_to "New recipe", new_recipe_path %>
<br></br>
<h2>Recipes</h2>
<ul>
  <% @recipes.each do |recipe| %>
    <h4><%= link_to recipe.title, recipe %></h4>
      <%= recipe.description %>
      <p>Prep time:  <%= recipe.preptime %></p>
      <p>Serves:  <%= recipe.servings %></p>
    <%= link_to "Edit Recipe ", edit_recipe_path(recipe) %> |
    <%= link_to "Delete Recipe ", recipe_path(recipe),
      :method => :delete,
      data: { confirm: 'Are you sure you want to delete this recipe?' } %>
    <br></br>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h2>New Recipe</h2>
<%= form_for(@recipe) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description, "Meal Type" %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :preptime, "Prep Time" %><br />
    <%= f.text_field :preptime %>
  </p>
  <p>
    <%= f.label :servings %><br />
    <%= f.text_field :servings %>
  </p>
  <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<%= title(@recipe.title, "Recipes") %>
<%= link_to "Back to Recipe List", recipes_path(@recipe)%>
<br></br>
  <h2><%= @recipe.title %></h2>
  <%= link_to "Edit Recipe ", edit_recipe_path(@recipe)%>
       |
  <%= link_to "Delete Recipe ", recipe_path(@recipe),
      :method => :delete,
      data: { confirm: 'Are you sure you want to delete this recipe?' }%>
  <p><%= @recipe.description %></p>
  <p>Prep time:  <%=@recipe.preptime %></p>
  <p>Serves:  <%=@recipe.servings %></p>
  <ul id='instructions'>
    <% @recipe.instructions.each do |instruction| %>
      <li>Ingredients: <%=instruction.ingredient %></li>
      <li>Directions: <%=instruction.directions %></li>
  </ul>
    <% end %>
  <h4><%= link_to "New Instruction", new_recipe_instruction_path(@recipe) %></h4>